# Generated by Django 2.2.1 on 2019-05-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('description', models.TextField(max_length=100)),
                ('body', models.TextField()),
                ('writer', models.CharField(max_length=25)),
            ],
        ),
    ]
