# Generated by Django 2.2.1 on 2019-05-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=15)),
                ('zip_code', models.IntegerField()),
                ('say_something', models.CharField(max_length=200)),
            ],
        ),
    ]
