# Generated by Django 2.2.6 on 2019-11-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191125_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('EDUCATIONAL', 'Educational'), ('TECHNOLOGY', 'Technology'), ('TUTORIAL', 'Tutorial'), ('NEWS', 'News')], max_length=20, null=True),
        ),
    ]
