# Generated by Django 2.2.6 on 2019-11-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191122_2241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='ContactMeData',
        ),
    ]
