# Generated by Django 2.2.6 on 2019-11-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_userlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
